---
  name: Deploy
  on:
    push:
      branches:
      - main
  jobs:
    deploy_lambda:
      name: Build, Push and Deploy lambda function
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: npm install
          env:
            CI: true
          run: |
            npm ci 
        - name: deploy
          run: | 
            zip -j deploy.zip ./src/*
            aws lambda update-function-code --function-name=$AWS_LAMBDA_NAME --zip-file=fileb://deploy.zip
          env:
           AWS_LAMBDA_NAME: ${{ secrets.AWS_LAMBDA_NAME }}
